'use client';

import { Sidebar } from "@/components/Sidebar";
import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Loader } from "lucide-react";
import { useFirestore, useDoc, useMemoFirebase } from "@/firebase";
import { doc } from "firebase/firestore";
import type { UserExamProfile } from "@/lib/user-exam-profile";
import GoalTracker from "@/components/GoalTracker";
import DailyMotivation from "@/components/DailyMotivation";

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const firestore = useFirestore();

  const userExamProfileRef = useMemoFirebase(() => {
    if (!firestore || !user?.uid) return null;
    return doc(firestore, 'users', user.uid, 'userExamProfile', user.uid);
  }, [firestore, user?.uid]);
  
  const { data: userExamProfile, isLoading: profileLoading } = useDoc<UserExamProfile>(userExamProfileRef);
  
  // This layout's ONLY security role is to handle logouts.
  // The root page handles the initial entry validation.
  useEffect(() => {
    if (!authLoading && !user) {
      router.replace('/auth/login');
    }
  }, [user, authLoading, router]);
  
  // While auth or profile is loading, show a loader.
  // This prevents rendering child pages with incomplete data.
  const isLoading = authLoading || profileLoading;
  if (isLoading) {
    return (
      <div className="min-h-screen w-full flex items-center justify-center bg-background">
        <Loader className="h-8 w-8 animate-spin text-primary" />
        <p className="ml-4 text-muted-foreground">Loading Dashboard...</p>
      </div>
    );
  }
  
  // The root RedirectPage should ensure user and profile exist before reaching here.
  // This is a final safeguard.
  if (!user || !userExamProfile) {
    // The useEffect above will trigger a redirect.
    return (
      <div className="min-h-screen w-full flex items-center justify-center bg-background">
        <Loader className="h-8 w-8 animate-spin text-primary" />
        <p className="ml-4 text-muted-foreground">Verifying Session...</p>
      </div>
    );
  }
  
  // If all data is present, render the full dashboard layout.
  return (
    <div className="min-h-screen w-full">
      <Sidebar />
      <main className="md:ml-[250px]">
        <div className="p-4 md:p-6 min-h-screen flex flex-col">
          <div 
            className="p-6 min-h-[calc(100vh-2rem)] md:min-h-[calc(100vh-3rem)] rounded-2xl glass flex-grow flex flex-col"
          >
            <GoalTracker 
              goalText={userExamProfile?.goalTrackerText} 
              homeState={userExamProfile?.homeState} 
            />
            <DailyMotivation />

            <div className="flex-grow">
              {children}
            </div>
          </div>
          <footer className="text-center py-4">
              <p className="text-xs text-muted-foreground">
                  Content on this platform is generated by SoniLearn's AI based on official exam trends and patterns. It is original and not copied from any external source.
              </p>
          </footer>
        </div>
      </main>
    </div>
  );
}
